version: "3.7"
services:
  zookeeper:
    image: zookeeper:3.8.0

  clickhouse-server:
    image: clickhouse/clickhouse-server:22.3.13.80-alpine
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
    volumes:
      - ./docker/config-main.xml:/etc/clickhouse-server/config.xml
      - ./docker/users.xml:/etc/clickhouse-server/users.xml

  clickhouse-server-replica:
    image: clickhouse/clickhouse-server:22.3.13.80-alpine
    ports:
      - "8124:8124"
      - "9001:9001"
      - "9005:9005"
    volumes:
      - ./docker/config-replica.xml:/etc/clickhouse-server/config.xml
      - ./docker/users.xml:/etc/clickhouse-server/users.xml
