version: "3.7"
services:
  ch_zookeeper:
    image: zookeeper:3.8.0
    container_name: ch-zookeeper
    network_mode: host

  clickhouse-server:
    image: clickhouse/clickhouse-server:22.3.13.80-alpine
    container_name: clickhouse-server
    network_mode: host
    volumes:
      - ./docker/config-main.xml:/etc/clickhouse-server/config.xml
      - ./docker/users.xml:/etc/clickhouse-server/users.xml

  clickhouse-server-replica:
    image: clickhouse/clickhouse-server:22.3.13.80-alpine
    container_name: clickhouse-server-replica
    network_mode: host
    volumes:
      - ./docker/config-replica.xml:/etc/clickhouse-server/config.xml
      - ./docker/users.xml:/etc/clickhouse-server/users.xml
