# .github/workflows/ci.yml
name: release

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0
      - uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
        with:
          java-version: 11
          distribution: temurin 
      - name: Release
        run: |
          git config --global user.email "gladiators@github.com"
          git config --global user.name "GitHub Gladiators Action"
          sbt "release with-defaults"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_USERNAME: "The-Analytics-Gladiators"
